### ISSUE TITLE
🐛 [BUG] - <title>Errors when running example files

### ISSUE THREAD

**Issue by renige** [UpstageAI/evalverse#24]
### Environment Settings

ubuntu 22.04
cuda 11.8
conda 24.3.0
python 3.10.12 

### Expected Behavior

..

### Actual Behavior

01_basic_usage.ipynb

model = "upstage/SOLAR-10.7B-Instruct-v1.0"
benchmark = "h6_en"

evaluator.run(model=model, benchmark=benchmark)

[2024-04-11 16:31:51][INFO][evalverse - evaluator.py:121] >> The value of argument "h6_en" has been changed to "True".
[2024-04-11 16:31:51][INFO][evalverse - evaluator.py:139] >> Args {'ckpt_path': 'upstage/SOLAR-10.7B-Instruct-v1.0', 'output_path': '/home/llm/workspace/evalverse/results', 'model_name': 'SOLAR-10.7B-Instruct-v1.0', 'use_fast_tokenizer': False, 'devices': '0', 'use_flash_attention_2': False, 'h6_en': True, 'batch_size': 16, 'use_vllm': False, 'gpu_memory_utilization': 0.8, 'model_parallel': 1, 'data_parallel': 1, 'load_in_8bit': False, 'load_in_4bit': False, 'mt_bench': False, 'baselines': None, 'judge_model': 'gpt-4', 'num_gpus_total': 1, 'num_gpus_per_model': 1, 'parallel_api': 1, 'ifeval': False, 'gpu_per_inst_eval': 1, 'eq_bench': False, 'eq_bench_prompt_type': 'ChatML', 'eq_bench_lora_path': None, 'eq_bench_quantization': None}
NCCL_P2P_DISABLE=1 lm_eval --model hf --model_args pretrained=upstage/SOLAR-10.7B-Instruct-v1.0,trust_remote_code=True,dtype=float16,use_fast_tokenizer=False,use_flash_attention_2=False --tasks arc_challenge --batch_size 16 --num_fewshot 25 --output_path /home/llm/workspace/evalverse/results/SOLAR-10.7B-Instruct-v1.0/h6_en/arc_challenge_25.json
Traceback (most recent call last):
  File "/home/llm/anaconda3/envs/llm/bin/lm_eval", line 5, in <module>
    from lm_eval.__main__ import cli_evaluate
  File "/home/llm/anaconda3/envs/llm/lib/python3.10/site-packages/lm_eval/__init__.py", line 1, in <module>
    from .evaluator import evaluate, simple_evaluate
  File "/home/llm/anaconda3/envs/llm/lib/python3.10/site-packages/lm_eval/evaluator.py", line 11, in <module>
    import lm_eval.api.metrics
  File "/home/llm/anaconda3/envs/llm/lib/python3.10/site-packages/lm_eval/api/metrics.py", line 7, in <module>
    import evaluate as hf_evaluate
  File "/home/llm/anaconda3/envs/llm/lib/python3.10/site-packages/evaluate/__init__.py", line 29, in <module>
    from .evaluation_suite import EvaluationSuite
  File "/home/llm/anaconda3/envs/llm/lib/python3.10/site-packages/evaluate/evaluation_suite/__init__.py", line 7, in <module>
    from datasets import Dataset, DownloadConfig, DownloadMode, load_dataset
  File "/home/llm/anaconda3/envs/llm/lib/python3.10/site-packages/datasets/__init__.py", line 18, in <module>
    from .arrow_dataset import Dataset
  File "/home/llm/anaconda3/envs/llm/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 60, in <module>
    import pyarrow as pa
  File "/home/llm/anaconda3/envs/llm/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: libaws-c-event-stream.so.1.0.0: cannot open shared object file: No such file or directory
[2024-04-11 16:31:53][INFO][evalverse - evaluator.py:183] >> arc_challenge_25shot done! exec_time: 0 min for upstage/SOLAR-10.7B-Instruct-v1.0

### Reproduction

..

**Comment by renige** [comment]
I solved it by referring to the site below
https://github.com/awslabs/aws-c-event-stream/#building
https://docs.github.com/ko/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account?platform=linux&tool=cli
